In [1]:
from turtle import shape
import scipy.io
import tensorflow as tf
from IPython.display import display, HTML
import pandas as pd
from tensorflow.python.keras.layers import Conv1D, MaxPooling1D, Dense, Dropout, Reshape, InputLayer, Flatten, GlobalMaxPooling1D 
from tensorflow.python.keras.models import Sequential
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
mat = scipy.io.loadmat(r'C:\Users\areak\Desktop\diploma\nine_movs_six_sub_cut.mat')

data_array = list()

for person_id in range(mat['nine_movs_six_sub_cut'].shape[0]):
    person_array = list()
    for movement_type in range(mat['nine_movs_six_sub_cut'][person_id][0][0][0].shape[0]):
        movement_array = list()
        for movement_id in range(mat['nine_movs_six_sub_cut'][person_id][0][0][0][movement_type][0].shape[0]):
            movement = mat['nine_movs_six_sub_cut'][person_id][0][0][0][movement_type][0][movement_id]
            movement_array.append(movement)
        person_array.append(movement_array)
    data_array.append(person_array)    

data = {'person_id':[0]*len(data_array[0][0]), 'movement_type': [0]*len(data_array[0][0]), 'data': data_array[0][0]}
df = pd.DataFrame(data)
for person_id in range(len(data_array)):
    for movement_type in range(len(data_array[person_id])):
        data = {'person_id':[person_id]*len(data_array[person_id][movement_type]), 'movement_type': [movement_type]*len(data_array[person_id][movement_type]), 'data': data_array[person_id][movement_type]}
        df_temp = pd.DataFrame(data)
        df = pd.concat([df,df_temp], ignore_index=True)
df.drop(labels=range(0,52), inplace=True)
df.reset_index(drop=True, inplace=True)

In [2]:
df

person_id  movement_type  \
0             0              0   
1             0              0   
2             0              0   
3             0              0   
4             0              0   
...         ...            ...   
2750          5              8   
2751          5              8   
2752          5              8   
2753          5              8   
2754          5              8   

                                                   data  
0     [-4.418776513645404, -4.541702191390394, -4.91...  
1     [-7.0242774593138195, -7.448422653649204, -7.5...  
2     [-3.7043726759918885, -3.7806589997386397, -3....  
3     [-4.7305250847632445, -4.7443395556938635, -4....  
4     [-6.904716423453932, -5.437790696030999, -5.66...  
...                                                 ...  
2750  [-4.526276777662932, -5.215224897776851, -5.49...  
2751  [-3.6944826800228667, -3.3679916595724557, -2....  
2752  [2.601504914660044, 2.0533762855250477, -0.227...  
2753  [-4.288644473957015, -4.242894030727987, -5.27...  
2754  [-8.766596771549676, -8.036991075591953, -7.81...  

[2755 rows x 3 columns]

In [111]:
X = np.asarray(df.data.tolist())
y = pd.get_dummies(np.asarray(df.movement_type))

In [112]:
print('X.shape: {0}'.format(X.shape))
print('y.shape: {0}'.format(y.shape))
display(X)
display(y)

X.shape: (2755, 400)
y.shape: (2755, 9)


array([[-4.41877651, -4.54170219, -4.91524819, ...,  4.0565058 ,
         4.05242879,  5.65152453],
       [-7.02427746, -7.44842265, -7.50548215, ..., -2.9629224 ,
        -3.21332283, -3.39444475],
       [-3.70437268, -3.780659  , -3.49432188, ..., -1.14724597,
        -0.3082993 , -0.41944267],
       ...,
       [ 2.60150491,  2.05337629, -0.22707116, ..., -3.19854831,
        -4.66440066, -6.09951469],
       [-4.28864447, -4.24289403, -5.27752555, ..., -1.909652  ,
        -3.17186104, -2.15547146],
       [-8.76659677, -8.03699108, -7.8171297 , ..., -3.15254152,
        -4.2394513 , -6.53087123]])

0  1  2  3  4  5  6  7  8
0     1  0  0  0  0  0  0  0  0
1     1  0  0  0  0  0  0  0  0
2     1  0  0  0  0  0  0  0  0
3     1  0  0  0  0  0  0  0  0
4     1  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. ..
2750  0  0  0  0  0  0  0  0  1
2751  0  0  0  0  0  0  0  0  1
2752  0  0  0  0  0  0  0  0  1
2753  0  0  0  0  0  0  0  0  1
2754  0  0  0  0  0  0  0  0  1

[2755 rows x 9 columns]

In [113]:
X_train, X_val, Y_train, Y_val = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

print('X_train.shape: {0}'.format(X_train.shape))
print('X_val.shape: {0}'.format(X_val.shape))
print('Y_train.shape: {0}'.format(Y_train.shape))
print('Y_val.shape: {0}'.format(Y_val.shape))
display(X_train)
display(X_val)
display(Y_train)
display(Y_val)

X_train.shape: (2066, 400)
X_val.shape: (689, 400)
Y_train.shape: (2066, 9)
Y_val.shape: (689, 9)


array([[ 7.95536979e+00,  7.69885467e+00,  6.24422889e+00, ...,
        -4.08055089e-01,  2.35200889e-01,  1.15749677e+00],
       [ 3.10166164e+00,  2.65734880e+00,  1.77560046e+00, ...,
         4.56988139e+00,  5.82258058e+00,  6.50614230e+00],
       [ 8.12593142e-03,  1.80152353e+00,  3.25086393e+00, ...,
        -4.41293787e+00, -4.59332227e+00, -3.03751774e+00],
       ...,
       [-1.91411646e+01, -1.99906720e+01, -1.95442645e+01, ...,
         3.08791198e+00,  2.75758875e+00,  3.69816245e+00],
       [-6.71240598e+00, -5.30552884e+00, -3.75525764e+00, ...,
         6.94982652e+00,  8.11535468e+00,  8.63177693e+00],
       [-1.74970385e+01, -1.72227845e+01, -1.78064953e+01, ...,
        -1.55498173e+00, -2.69656554e+00, -3.93014336e+00]])

array([[-9.66975537, -6.22339724, -4.05921714, ...,  3.08854671,
         2.87856972,  2.96426638],
       [-2.26114458, -1.42943756, -0.57403428, ...,  0.60515809,
        -0.27470216, -1.16703452],
       [ 0.62542654,  2.59476606,  2.15541759, ...,  2.0153089 ,
         5.29177797,  7.34432208],
       ...,
       [-0.81022461, -0.66051195, -2.16648814, ..., -7.64985809,
        -7.81084019, -8.24103234],
       [ 2.71666364,  2.06448651,  1.20863461, ..., -1.50107206,
        -0.06324383, -1.15448821],
       [ 0.36443876, -0.01309921,  0.59058168, ..., -3.08849322,
        -3.83066843, -3.65055651]])

0  1  2  3  4  5  6  7  8
444   0  0  0  0  0  0  0  1  0
1219  0  0  0  0  0  0  1  0  0
1133  0  0  1  0  0  0  0  0  0
390   0  0  0  0  0  0  1  0  0
2152  0  0  0  0  0  0  1  0  0
...  .. .. .. .. .. .. .. .. ..
478   0  0  0  0  0  0  0  0  1
603   0  1  0  0  0  0  0  0  0
1623  0  0  0  0  0  0  1  0  0
2458  0  0  0  1  0  0  0  0  0
1807  0  1  0  0  0  0  0  0  0

[2066 rows x 9 columns]

0  1  2  3  4  5  6  7  8
703   0  0  0  1  0  0  0  0  0
1693  0  0  0  0  0  0  0  1  0
1634  0  0  0  0  0  0  1  0  0
1381  0  1  0  0  0  0  0  0  0
941   0  0  0  0  0  0  0  1  0
...  .. .. .. .. .. .. .. .. ..
1422  0  1  0  0  0  0  0  0  0
1272  0  0  0  0  0  0  0  1  0
392   0  0  0  0  0  0  1  0  0
802   0  0  0  0  0  1  0  0  0
516   0  0  0  0  0  0  0  0  1

[689 rows x 9 columns]

In [114]:
classes = 9

model = Sequential()
model.add(InputLayer(input_shape=(400,)))
model.add(Reshape((400,1), input_shape=(400,)))
model.add(Conv1D(100,30,activation='relu',input_shape=(400,1)))
model.add(Conv1D(100,30,activation='relu'))
model.add(Conv1D(100,30,activation='relu'))
model.add(MaxPooling1D(3))
model.add(Conv1D(200,30,activation='relu'))
model.add(Conv1D(200,30,activation='relu'))
model.add(GlobalMaxPooling1D())
model.add(Dropout(0.3))
model.add(Flatten())
model.add(Dense(300, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(classes, activation='softmax'))

model.compile(optimizer = 'Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [115]:
model.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_16 (Reshape)         (None, 400, 1)            0         
_________________________________________________________________
conv1d_60 (Conv1D)           (None, 371, 100)          3100      
_________________________________________________________________
conv1d_61 (Conv1D)           (None, 342, 100)          300100    
_________________________________________________________________
conv1d_62 (Conv1D)           (None, 313, 100)          300100    
_________________________________________________________________
max_pooling1d_14 (MaxPooling (None, 104, 100)          0         
_________________________________________________________________
conv1d_63 (Conv1D)           (None, 75, 200)           600200    
_________________________________________________________________
conv1d_64 (Conv1D)           (None, 46, 200)         

In [116]:
EPOCHS = 30
history = model.fit(X_train, Y_train, epochs=EPOCHS, verbose=2,validation_data=(X_val, Y_val))
plt.figure(figsize=(10,6))
plt.plot(history.history['accuracy'], label = 'train_accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()
print(history.history['val_accuracy'])

Epoch 1/30
65/65 - 23s - loss: 2.2134 - accuracy: 0.1742 - val_loss: 1.8886 - val_accuracy: 0.2583
Epoch 2/30
65/65 - 26s - loss: 1.7462 - accuracy: 0.3393 - val_loss: 1.5682 - val_accuracy: 0.4122
Epoch 3/30


KeyboardInterrupt: 